# Generated by Django 5.2.1 on 2025-05-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actors_directors_hall_movie_movieactors_movie_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cinema.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
